source("http://bioconductor.org/biocLite.R")
biocLite("CAMERA")
biocLite("xcms")
biocLite("BiGGR")
biocLite("cosmiq")
biocLite("iontree") 
biocLite("MAIT") 
biocLite("Metab") 
biocLite("metabomxtr") 
biocLite("mQTL.NMR") 
biocLite("mzR") 
biocLite("metaMS") 
biocLite("OmicsMarkeR") 
biocLite("PAPi") 
biocLite("pathview") 
biocLite("Rdisop") 
biocLite("RMassBank") 
biocLite("SIMAT") 
install.packages("rsm", , repos='http://mirrors.ebi.ac.uk/CRAN') 
install.packages("devtools",, repos='http://mirrors.ebi.ac.uk/CRAN')
library("devtools")
install_github("glibiseller/IPO") 
